title: Project

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          title:
            label: Title
            type:  text
            width: 3/4

          text:
            label: Text
            type:  textarea

  - width: 1/3
    sections:
      images:
        headline: Project Images
        type: files
        template: captionedimage
        sortable: true 

  
