title: Project

sections:
  images:
    headline: Project Images
    type: files
    template: captionedimage
    sortable: true 

  content:
    type: fields
    fields:
      title:
        label: Title
        type:  text
        width: 3/4

      text:
        label: Text
        type:  textarea

 
